language: python
python:
  - "3.6"
  - "3.7"  
  - "3.8"  
env:
  matrix:
    - DJANGO_VERSION=2.2
    - DJANGO_VERSION=3.0
install:
  - pip install coverage # coverage>=4 has issues with python3
  - pip install -q Django==$DJANGO_VERSION coveralls
  - python setup.py egg_info
script: coverage run --source='dj_pagination' --omit *runner*,*test_project* setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
# matrix:
#   exclude:
#     - python: "2.7"
#       env: DJANGO_VERSION=2.0
#     - python: "2.7"
#       env: DJANGO_VERSION=2.1
#     - python: "2.7"
#       env: DJANGO_VERSION=2.2
#     - python: "3.4"
#       env: DJANGO_VERSION=2.1
#     - python: "3.4"
#       env: DJANGO_VERSION=2.2
